language: ruby
rvm:
  - 2.1.0

before_install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.1.tar.gz | tar xz -C /tmp

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - psql -c 'create database travis_ci_test;' -U postgres
  - TEST_CLUSTER_COMMAND="/tmp/elasticsearch-1.0.1/bin/elasticsearch" rake elasticsearch:start

addons:
  code_climate:
    repo_token: ef43aa10c90a51912f6c6cb6dce1874f667bb8aea5a7ac77e74e6dda3fb9dd16